#!/bin/bash
dir=$1
shift
mkdir -p $dir
archive=$1
shift
IFS=$'\n'
for ext in "$@"
do
	regex=*.$ext
	files=$(find ~ -name $regex)
	for file in $files
	do
		cp --parents $file $dir
	done
done
tar -czf $archive $dir
echo "Done"
